#!/usr/bin/env python3

import psycopg2

translations = {
    "ტექნიკა": "technology",
    "ფოტო და ვიდეო": "photo and video",
    "ციფრული კამერის აქსესუარები": "digital camera accessories",
    "მობილური ტელეფონები და აქსესუარები": "mobile phones and accessories",
    "მობილური ტელეფონის აქსესუარები": "mobile phone accessories",
    "ექშენ კამერა": "action camera",
    "ბინოკლი": "binoculars",
    "ტელესკოპი": "telescope",
    "დრონი": "drone",
    "დრონის აქსესუარები": "drone accessories",
    "ციფრული კამერა": "digital camera",
    "მიკროსკოპი": "microscope",
    "Micro SD ბარათი": "micro sd card",
    "ვიდეო კამერა": "video camera",
    "თავის მოვლა": "hair care",
    "თმის ფენი": "hair dryer",
    "თმის უთო": "hair straightener",
    "წვერსაპარსი": "beard trimmer",
    "ტრიმერი": "trimmer",
    "თმის სახვევი": "hair curler",
    "სახლის და ეზოს მოვლა": "home and yard care",
    "მტვერსასრუტი": "vacuum cleaner",
    "მოპი და იატაკის საწმენდი": "mop and floor cleaner",
    "მტვერსასრუტის აქსესუარები": "vacuum cleaner accessories",
    "რობოტი მტვერსასრუტი": "robot vacuum cleaner",
    "მაღალი წნევით მრეცხავი": "pressure washer",
    "ტელევიზორები და აუდიო სისტემები": "tv and audio systems",
    "ტელევიზორი": "tv",
    "აუდიო სისტემები": "audio systems",
    "კომპიუტერული ტექნიკა და აქსესუარები": "computer equipment and accessories",
    "კომპიუტერის აქსესუარები": "computer accessories",
    "კედლის საკიდი": "wall mount",
    "კაბელები და ადაპტერები": "cables and adapters",
    "პროექტორი": "projector",
    "პროექტორის აქსესუარები": "projector accessories",
    "გეიმინგი": "gaming",
    "სათამაშო კონსოლები": "gaming consoles",
    "PlayStation-ის აქსესუარები": "playstation accessories",
    "Xbox": "xbox",
    "მონიტორი": "monitor",
    "გეიმინგ სისტემური ბლოკი": "gaming pc",
    "PC კომპონენტები": "pc components",
    "ნოუთბუქი": "laptop",
    "გეიმინგ აქსესუარები": "gaming accessories",
    "ნოუთბუქის აქსესუარები": "laptop accessories",
    "მსხვილი საყოფაცხოვრებო ტექნიკა": "large appliances",
    "მაცივარი": "refrigerator",
    "სარეცხი მანქანა": "washing machine",
    "საშრობი მანქანა": "dryer",
    "წვრილი საოჯახო ტექნიკა": "small household appliances",
    "ყავის მოყვარულთათვის": "for coffee lovers",
    "სამზარეულოს წვრილი ტექნიკა": "small kitchen appliances",
    "ხორცსაკეპი": "meat grinder",
    "ჭკვიანი სახლი": "smart home",
    "ჭკვიანი განათება": "smart lighting",
    "ჭკვიანი კამერა": "smart camera",
    "ჭკვიანი სენსორები": "smart sensors",
    "საკვების დოზატორი": "pet feeder",
    "ჭკვიანი ჩამრთველები": "smart switches",
    "ჭკვიანი სახლის აქსესუარები": "smart home accessories",
    "კონტროლი და ავტომატიზაცია": "control and automation",
    "ჭკვიანი საკეტები": "smart locks",
    "მობილური ტელეფონები": "mobile phones",
    "პორტატული დინამიკი": "portable speaker",
    "უსადენო ყურსასმენი": "wireless headphones",
    "სმარტ საათები": "smartwatches",
    "ტაბი": "tablet",
    "მშობელი და ბავშვი": "parent and baby",
    "ბავშვის მოვლა": "baby care",
    "საბავშვო ელექტრო ჯაგრისი": "baby electric toothbrush",
    "რადიო ძიძა": "baby monitor radio",
    "ძიძა კამერა": "baby monitor camera",
    "რძის ელექტრო გამოსაწველი": "electric breast pump",
    "საბავშვო სასწორი": "baby scale",
    "ბავშვის საკვების მოსამზადებელი": "baby food maker",
    "კანის მოვლა": "skin care",
    "ეპილატორი": "epilator",
    "მასაჟორი": "massager",
    "ელექტრო ჯაგრისები & ირიგატორები": "electric toothbrushes and irrigators",
    "სასწორი": "scale",
    "სარბენი ბილიკი": "treadmill",
    "წვერსაპარსის თავაკი": "beard trimmer heads",
    "უთო": "iron",
    "ორთქლით მწმენდავი": "steam cleaner",
    "უთოს აქსესუარები": "iron accessories",
    "შუშის საწმენდები": "glass cleaners",
    "ბაღის და ეზოს ინვენტარი": "garden and yard tools",
     "სახლის და ეზოს მოვლა ": "home and yard care",
    "ტელევიზორის აქსესუარები": "tv accessories",
    "PlayStation ის აქსესუარები": "playstation accessories",
    "სისტემური ბლოკი": "desktop pc",
    "ჭურჭლის სარეცხი მანქანა": "dishwasher",
    "გაზქურა": "gas stove",
    "ჩასაშენებელი ტექნიკა": "built in appliances",
    "სამზარეულოს ტექნიკის აქსესუარები": "kitchen appliance accessories",
    "მიკროტალღური ღუმელი": "microwave oven",
    "პორტატული დამტენი/ფაუერ ბანკი": "power bank",
    "ნოუთბუქის ქულერი": "laptop cooler",
    "ნოუთბუქის ჩანთა": "laptop bag",
    "ნოუთბუქის დამტენი": "laptop charger",
    "ტაბის აქსესუარები": "tablet accessories",
    "მანქანის ხელსაწყოები და აქსესუარები": "car tools and accessories",
    "მანქანის აკუმულატორისთვის": "for car battery",
    "მანქანის საბურავებისთვის": "for car tires",
    "მანქანის ვიდეო რეგისტრატორები": "car dvr",
    "სერვისები": "services",
    "ლეპტოპის სერვისები": "laptop services",
    "მობილური ტელეფონის სერვისები": "mobile phone services",
    "ტაბის სერვისები": "tablet services",
    "გამწოვი": "exhaust fan",
    "კლიმატური ტექნიკა": "climate control",
    "კონდიციონერი": "air conditioner",
    "ჰაერის გამწმენდი & დამატენიანებელი": "air purifier and humidifier",
    "საყოფაცოვრებო ტექნიკის აქსესუარები": "household appliance accessories",
    "ვენტილატორი": "fan",
    "ორთქლის კარადა": "steam closet",
    "სლაისერი": "slicer",
    "უსადენო დამტენი": "wireless charger",
    "USB კაბელი": "usb cable",
    "მანქანის დამტენი": "car charger",
    "მობილურის სადგამი": "phone holder",
    "სმარტ საათის აქსესუარები": "smartwatch accessories",
    "დამტენი ადაპტერი": "charging adapter",
    "ტაბის კლავიატურა": "tablet keyboard",
    "პანელური კომპიუტერი ": "all in one pc",
    "მონიტორის აქსესუარები": "monitor accessories",
    "დამცავი ქეისი": "protective case",
    "ჩასაშენებელი ყავის აპარატი": "built in coffee machine",
    "აეროგრილი": "air fryer",
    "ბლენდერი და ჩოპერი": "blender and chopper",
    "ტოსტერი": "toaster",
    "პიცის საცხობი": "pizza oven",
    "ელექტრო ჩაიდანი": "electric kettle",
    "სამზარეულოს სასწორი": "kitchen scale",
    " რძის ამომყვანი": "milk frother",
    "ყავის აპარატის აქსესუარები": "coffee machine accessories",
    "კვების ბლოკი": "power supply",
    "დედა დაფა": "motherboard",
    "მყარი დისკი/SSD": "hard drive ssd",
    "ქულერი": "cooler",
    "ბეჭდვა და კოპირება": "printing and copying",
    "ქსელური მოწყობილობები": "network devices",
    "ქსელის გამანაწილებელი/სვიჩი": "network switch",
    "კლავიატურა": "keyboard",
    "სმარტ სათვალე": "smart glasses",
    "მაუსი": "mouse",
    "კომპიუტერის ვებკამერა": "webcam",
    "პორტატული ელექტრო სადგურები": "portable power stations",
    "USB გამანაწილებლები": "usb hubs",
    "მზის პანელი": "solar panel",
    "კვების წყაროები": "power sources",
    "ყურსასმენის აქსესუარები": "headphone accessories",
    "ყავის აპარატი": "coffee machine",
    "ყავის მადუღარა": "coffee maker",
    "ყავა": "coffee",
    "ელექტრო ტრანსპორტი": "electric transport",
    "ელექტრო სკუტერი": "electric scooter",
    "ელექტრო სკუტერის აქსესუარები": "electric scooter accessories",
}

print("  SQL Update Statements for Category Slugs")
print("  Generated from Georgian to English translations\n")

conn = psycopg2.connect("postgresql://postgres:postgres@localhost:5432/ecommerce")
cur = conn.cursor()

for georgian_name, english_slug in translations.items():
    cur.execute(f"update categories set slug='{english_slug}' where name='{georgian_name}'")
    print(f"UPDATE categories SET slug = '{english_slug}' WHERE name = '{georgian_name}';")

cur.close()
conn.commit()